#!/usr/bin/env python3
"""Regenerate the bundled Material Symbols icon subset + codepoint map.

The app renders icons by codepoint from a self-hosted subset of Material Symbols
Rounded (no runtime Google Fonts download). When you add a new `<Icon name="…">`,
add the name to USED below and run:

    python3 scripts/build-icons.py

Requires: fonttools + brotli  (pip install fonttools brotli)
Outputs:  static/fonts/material-symbols-rounded.woff2
          src/lib/content/iconCodepoints.ts
"""
import os
import urllib.request
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_URL = "https://github.com/google/material-design-icons/raw/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf"
CODEPOINTS_URL = "https://github.com/google/material-design-icons/raw/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints"

# Every icon name the app references (literal + dynamic), plus a small buffer.
USED = """
add arrow_back arrow_drop_down arrow_upward auto_awesome block bookmark
bookmark_border bookmarks check check_box check_box_outline_blank chevron_left
chevron_right close cloud_off code collections comment delete description
download edit explore expand_less expand_more favorite folder forum forward
fullscreen fullscreen_exit home image info link lock menu notifications_active
open_in_new pause person play_arrow public push_pin refresh search settings
share system_update upload visibility visibility_off volume_off volume_up whatshot
more_vert content_copy flag notifications done remove star arrow_forward warning
""".split()


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    return urllib.request.urlopen(req, timeout=60).read()


def main() -> None:
    ttf = "/tmp/MaterialSymbolsRounded.ttf"
    if not os.path.exists(ttf):
        open(ttf, "wb").write(fetch(FONT_URL))
    codepoints = fetch(CODEPOINTS_URL).decode()

    cps = {}
    for line in codepoints.splitlines():
        line = line.strip()
        if line:
            name, hex_ = line.split()
            cps[name] = int(hex_, 16)

    missing = [n for n in USED if n not in cps]
    if missing:
        raise SystemExit(f"names not in codepoints file: {missing}")

    used = sorted(set(USED))
    unicodes = [cps[n] for n in used]

    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = []  # rendered by codepoint, so no ligatures needed
    opts.name_IDs = []
    opts.notdef_outline = True
    font = subset.load_font(ttf, opts)
    ss = subset.Subsetter(options=opts)
    ss.populate(unicodes=unicodes)
    ss.subset(font)
    out_font = os.path.join(ROOT, "static/fonts/material-symbols-rounded.woff2")
    subset.save_font(font, out_font, opts)

    cmap = TTFont(out_font).getBestCmap()
    missing_glyphs = [n for n in used if cps[n] not in cmap]
    if missing_glyphs:
        raise SystemExit(f"codepoints missing from subset cmap: {missing_glyphs}")

    out_ts = os.path.join(ROOT, "src/lib/content/iconCodepoints.ts")
    with open(out_ts, "w") as f:
        f.write("// GENERATED by scripts/build-icons.py — do not edit by hand.\n")
        f.write("// Material Symbols Rounded icon name -> the codepoint character the\n")
        f.write("// bundled subset font renders. Regenerate when adding a new icon.\n\n")
        f.write("export const ICON_CODEPOINTS: Record<string, string> = {\n")
        for n in used:
            f.write(f"\t{n!r}: '\\u{cps[n]:04x}',\n")
        f.write("};\n")

    print(f"OK: {len(used)} icons -> {os.path.getsize(out_font)} bytes; cmap verified")


if __name__ == "__main__":
    main()
